import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useState } from 'react';
import Router from 'next/router';

const Form = () => {
  //define local state hooks for each form element:
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [blogurl, setBlogurl] = useState('');
  const [feedurl, setFeedurl] = useState('');
  const [notes, setNotes] = useState('');
  const [response, setResponse] = useState('');

  const handleSubmit = async (event) => {
    event.preventDefault();
    try {
      const res = await fetch('/api/blog', {
        method: 'POST',
        body: JSON.stringify({ name, email, blogurl, feedurl, notes }),
        headers: { 'Content-Type': 'application/json' },
      });

      const json = await res.json();
      if (json.success) {
        alert('Thank you for submitting your blog!');
        Router.push('/');
      } else {
        setResponse(json.message);
      }
    } catch (error) {
      setResponse('An error occured while submitting the form');
    }
  };

  // use them for each input element, adding the value as the value attribute, and the update function in the onChange handler function
  return (
    <div>
      <Head>
        <title>Blogsy - Add New Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@tailwindcss/ui@latest/dist/tailwind-ui.min.css"
        />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Blogsy</h1>

        <p className={styles.description}>
          Add your favorite blog RSS down below
        </p>
        <p>
          <Link href="/form">
            <p className="underline cursor-pointer mt-2">
              <a>Back to Homepage</a>
            </p>
          </Link>
        </p>
      </main>
      <main>
        <p className="text-center pb-5">{response}</p>

        <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
          <div>
            <div className="max-w-3xl mx-auto sm:px-6 lg:px-8">
              <form
                className="mt-5 md:mt-0 md:col-span-2"
                action=""
                method="POST"
                onSubmit={handleSubmit}
              >
                <div className="shadow sm:rounded-md sm:overflow-hidden">
                  <div className="px-4 py-5 bg-white sm:p-6">
                    <label className="block text-sm font-medium leading-5 text-gray-700">
                      Blog name / owner name
                    </label>
                    <input
                      required
                      value={name}
                      onChange={(event) => setName(event.target.value)}
                      className="mb-5 mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5"
                    />
                    <label className="block text-sm font-medium leading-5 text-gray-700">
                      Email address
                    </label>
                    <input
                      required
                      type="email"
                      value={email}
                      onChange={(event) => setEmail(event.target.value)}
                      className="mb-5 mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5"
                    />
                    <label className="block text-sm font-medium leading-5 text-gray-700">
                      Blog URL
                    </label>
                    <input
                      type="url"
                      required
                      value={blogurl}
                      onChange={(event) => setBlogurl(event.target.value)}
                      className="mb-5 mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5"
                      placeholder="https://www.example.com"
                    />
                    <label className="block text-sm font-medium leading-5 text-gray-700">
                      RSS Feed URL
                    </label>
                    <input
                      type="url"
                      required
                      value={feedurl}
                      onChange={(event) => setFeedurl(event.target.value)}
                      className="mb-5 mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5"
                      placeholder="https://www.example.com/feed"
                    />

                    <label
                      htmlFor="about"
                      className="block text-sm leading-5 font-medium text-gray-700"
                    >
                      Notes
                    </label>
                    <div className="rounded-md shadow-sm">
                      <textarea
                        value={notes}
                        onChange={(event) => setNotes(event.target.value)}
                        rows="3"
                        className="form-textarea mt-1 block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5"
                        placeholder="Anything you want to tell us!"
                      ></textarea>
                    </div>
                    <p className="mt-2 text-sm text-gray-500">
                      Your submission will be approved before appearing on the
                      site
                    </p>
                  </div>
                  <div className="px-4 py-3 bg-gray-50 text-right sm:px-6">
                    <span className="inline-flex rounded-md shadow-sm">
                      <button
                        type="submit"
                        className="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-blue-600 hover:bg-blue-500 focus:outline-none focus:border-blue-700 focus:shadow-outline-blue active:bg-blue-700 transition duration-150 ease-in-out"
                      >
                        Save
                      </button>
                    </span>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Form;
